version: '3.1'

services:
  mariadb:
    container_name: mariadb
    image: mariadb:10.6
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      - PMA_HOST = mariadb
      - PMA_PORT = 3307
      - PMA_ARBITRARY=1
    depends_on:
      mariadb:
        condition: service_started

  smtp4dev:
    container_name: SmtpMailer
    image: rnwood/smtp4dev:v3
    restart: always
    ports:
      # Change the number before : to the port the web interface should be accessible on
      - "9081:80"
      # Change the number before : to the port the SMTP server should be accessible on
      - "1025:25"
    depends_on:
      phpmyadmin:
        condition: service_started