spring:
  datasource:
    url: jdbc:mariadb://localhost:3307/cefim_voyage?createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create-drop
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  mail:
    host: localhost
    port: 1025

server:
  port: 8080
  servlet:
    context-path: /api
  forward-headers-strategy: framework